# Generated by Django 4.1.3 on 2022-11-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apertur_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FB',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='heading', max_length=25)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='heading', max_length=25)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
