# Generated by Django 4.1.3 on 2022-11-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apertur_app', '0002_fb_jewellery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_video',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='heading', max_length=25)),
                ('Video', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
