# Generated by Django 4.1.3 on 2022-11-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apertur_app', '0004_alter_banner_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
