# Generated by Django 4.1.3 on 2023-01-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apertur_app', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelegance',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='heading', max_length=25)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
